# https://golangci-lint.run/usage/configuration
version: "2"

run:
  timeout: 5m
  tests: true
  concurrency: 4

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - revive
    - ineffassign
    - unused
    - misspell
    - nakedret
    - bodyclose
    - gocritic
    - makezero
    - gosec

formatters:
  enable:
    - gci
    - gofmt
    - goimports
    - golines

output:
  formats:
    text:
      print-linter-name: true
      print-issued-lines: true
