name: Build and Test Go Project
on: [ push, pull_request ]

permissions:
  contents: read

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      - name: Download dependencies
        run: go mod download

      - name: Run unit tests
        run: script/test

      - name: Prepare build_info files
        shell: bash
        run: |
          BUILD_DATE=$(date -u +%Y-%m-%dT%H:%M:%SZ)
          mkdir -p cmd/github-mcp-server/build_info
          echo "${{ github.sha }}" > cmd/github-mcp-server/build_info/commit.txt
          echo "$BUILD_DATE" > cmd/github-mcp-server/build_info/date.txt
          if [ "${{ github.event_name }}" = "push" ]; then
            echo "${{ github.ref_name }}" > cmd/github-mcp-server/build_info/version.txt
          else
            echo "pr-${{ github.event.pull_request.number }}" > cmd/github-mcp-server/build_info/version.txt
          fi
      - name: Build
        run: go build -v ./cmd/github-mcp-server
